export const ROLES = {
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
  ACCOUNTANT: 'ACCOUNTANT',
  TERMINAL_OPERATOR: 'TERMINAL_OPERATOR',
  DRIVER: 'DRIVER',
  WATCHMAN: 'WATCHMAN',
}

export const ROLE_LABELS = {
  [ROLES.ADMIN]: 'Admin',
  [ROLES.SUPER_ADMIN]: 'Owner / CEO',
  [ROLES.ACCOUNTANT]: 'Accountant',
  [ROLES.TERMINAL_OPERATOR]: 'Terminal Operator',
  [ROLES.DRIVER]: 'Driver',
  [ROLES.WATCHMAN]: 'Watchman / Gate Checker',
}

export const ROLE_LOGIN_ORDER = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN,
  ROLES.ACCOUNTANT,
  ROLES.TERMINAL_OPERATOR,
  ROLES.DRIVER,
  ROLES.WATCHMAN,
]
