export const CONSIGNMENT_STATUSES = {
  CREATED: 'CREATED',
  LOADED: 'LOADED',
  IN_TRANSIT: 'IN_TRANSIT',
  AT_GATE: 'AT_GATE',
  VERIFIED_FOR_RELEASE: 'VERIFIED_FOR_RELEASE',
  DELIVERED: 'DELIVERED',
  FLAGGED: 'FLAGGED',
  CLOSED: 'CLOSED',
}

export const PAYMENT_STATUSES = {
  NOT_SUBMITTED: 'NOT_SUBMITTED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  FLAGGED: 'FLAGGED',
  REJECTED: 'REJECTED',
}

export const ALERT_STATUSES = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  CRITICAL: 'CRITICAL',
  RESOLVED: 'RESOLVED',
}

export const PAYMENT_METHODS = ['CASH', 'BANK', 'JAZZCASH', 'EASYPAISA']

export const CONSIGNMENT_TRANSITIONS = {
  [CONSIGNMENT_STATUSES.CREATED]: [CONSIGNMENT_STATUSES.LOADED],
  [CONSIGNMENT_STATUSES.LOADED]: [CONSIGNMENT_STATUSES.IN_TRANSIT],
  [CONSIGNMENT_STATUSES.IN_TRANSIT]: [CONSIGNMENT_STATUSES.AT_GATE],
  [CONSIGNMENT_STATUSES.AT_GATE]: [CONSIGNMENT_STATUSES.VERIFIED_FOR_RELEASE],
  [CONSIGNMENT_STATUSES.VERIFIED_FOR_RELEASE]: [CONSIGNMENT_STATUSES.DELIVERED],
  [CONSIGNMENT_STATUSES.DELIVERED]: [CONSIGNMENT_STATUSES.CLOSED],
  [CONSIGNMENT_STATUSES.FLAGGED]: [CONSIGNMENT_STATUSES.AT_GATE],
}
